config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  authenticated :user do
    root to: 'users#show', as: :authenticated_root
  end

  resources :users, only: [:show, :update, :edit, :destroy]

  resources :pools do
    resources :pool_profiles
    get :match
  end

  resources :pods, only: [:index, :show] do
    delete :leave
    put :messages_seen
    patch :messages_seen
  end

  resources :swipes, only: [:create]

  match "/websocket", :to => WebsocketRails::ConnectionManager.new, via: [:get, :post]

  get '/:id', to: 'pools#show'
end

app/models/pool.rb
class Pool < ActiveRecord::Base
  extend FriendlyId

  has_many :users, through: :pool_profiles
  has_many :pool_profiles
  has_many :pods
  belongs_to :creator, class_name: 'User'


  friendly_id :slug_candidates, use: :slugged

  private

  def slug_candidates
    [
      :name,
      [:name, :location_name],
      [:name, :location_name, :id]
    ]
  end

end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController

  before_action :set_pool, only: [:show, :update, :edit, :destroy]
  before_action :authenticate_user!, except: :show

  respond_to :html

  def index
    @pools = Pool.all
    respond_with @pools
  end

  def show
    if !user_signed_in?
      store_location_for :user, pool_path(@pool)
    end
    respond_with @pool
  end

  def new
    @pool = Pool.new
    respond_with @pool
  end

  def create
    @pool = Pool.new pool_params
    @pool.creator_id = current_user.id
    flash[:notice] = 'Pool was successfully created.' if @pool.save
    #respond_with @pool
    redirect_to :root
  end

  def update
    @pool.update pool_params
    respond_with @pool
  end

  def edit
    respond_with @pool
  end

  def destroy
    @pool.destroy
    redirect_to :root
  end

  def match
    @pool = current_user.pools.friendly.find params[:pool_id]
    @next_pp = PoolProfile.next(current_user, @pool)
  end

  private

  def set_pool
    @pool = Pool.friendly.find params[:id]
  end

  def pool_params
    params.require(:pool).permit(:name, :description, :start_at, 
                  :end_at, :location_name, :location_address)
  end

end

app/views/pools/_form.html.erb
<%= form_for @pool do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </p>

  <p>
    <%= f.label :location_name %><br>
    <%= f.text_field :location_name, class: "form-control" %>
  </p>

  <p>
    <%= f.label :location_address %><br>
    <%= f.text_field :location_address, class: "form-control" %>
  </p>

  <p>
    <%= f.label :start_date %><br>
    <%= f.datetime_select(:start_at) %>
  </p>

  <p>
    <%= f.label :end_date %><br>
    <%= f.datetime_select(:end_at) %>
  </p>

  <p>
    <%= f.submit class: "btn btn-primary btn-block" %>
  </p>
<% end %>

app/views/pools/edit.html.erb
<% content_for :nav_left do %>
  <%= nav_item_discover "left" %>
<% end %>
<% content_for :nav_right do %>
  <%= nav_item_chat "right" %>
<% end %>

<div class="container">

  <% #Create new pool %>
  <div class="row">
    <div class="col-xs-12 col-md-4 col-md-offset-4">
      <span class="name">Edit Event</span>
      <%= render partial: 'form' %>
    </div>
  </div>
</div>

app/views/pools/index.html.erb
<% content_for :nav_left do %>
  <%= nav_item_events "left" %>
<% end %>
<% content_for :nav_right do %>
  <%= nav_item_chat "right" %>
<% end %>

<div class="container">

  <div class="row">
    <div class="col-xs-12 col-md-4 col-md-offset-4 custom-list">

      <div class="list-group list-pool-items">
        <a class="list-group-title">Discover Events</a>
        <% @pools.each do |pool| %>
          <%= render partial: 'shared/list_pool', locals: { pool: pool } %>
        <% end %>
      </div>

    </div>
  </div>

</div>

app/views/pools/match.html.erb
<% content_for :nav_left do %>
  <%= nav_item_events "left" %>
<% end %>
<% content_for :nav_right do %>
  <%= nav_item_chat "right" %>
<% end %>
<div id='swiper'>
<div class='container'>
  <div class='row'>
      <% if @next_pp.nil? %>
        <div class='col-md-4 col-md-offset-4 card'>
          <p class='empty'>
          You're the only one here :( ...
          </p>
        </div>
      <% else %>
        <div class='col-md-4 col-md-offset-4 card'>
        <% user = @next_pp.user %>

        <div class='profile-info'>
          <div class='row'>
            <div class='avatar col-xs-4 col-xs-offset-4'>
              <%= image_tag user.avatar %>
            </div>
          </div>

          <div class='name'>
            <%= user.name %>
          </div>

          <div class='skills'>
            <span class='profile-label'>Skills:</span>
            <span class='skills-data'>
              <% if @next_pp.skills %>
                <%= @next_pp.skills %>
              <% else %>
                <em>No skills entered.</em>
              <% end %>
            </span>
          </div>

          <div class='goals'>
            <span class='profile-label'>Goals:</span>
            <span class='goals-data'>
              <% if @next_pp.goals %>
                <%= @next_pp.goals %>
              <% else %>
                <em>No goals entered.</em>
              <% end %>
            </span>
          </div>
        </div>

        <% if pod = user.pods.find_by(pool_id: @pool.id) %>
          <% if pod.present? && pod.users.count > 0 %>
            <div class='pod-users'>
              <span>Pod members</span>
              <span class='pod-avatars'>
                <% pod.users.each do |pod_user| %>
                  <% if pod_user != user %>
                    <%= image_tag pod_user.avatar %>
                  <% end %>
                <% end %>
              </span>
            </div>
          <% end %>
        <% end %>
        </div>

        <div class='col-md-4 col-md-offset-4 actions'>
          <button id='skip-btn' class='action-btn skip' title='Skip'><%= fa_icon 'times' %></button>
          <button id='accept-btn' class='action-btn accept' title='Accept'><%= fa_icon 'check' %></button>
        </div>
      <% end %>
  </div>
</div>
</div>

<script>
<% if @next_pp.present? %>
(function($) {

  var currentProfileID = <%= @next_pp.id %>;
  var poolID = <%= @pool.id %>;

  var $skipBtn = $('#skip-btn');
  var $acceptBtn = $('#accept-btn');

  var $card = $('.card');

  $skipBtn.click(function() {
    sendSwipe(false);
  });

  $acceptBtn.click(function() {
    sendSwipe(true);
  });

  function sendSwipe(rightSwipe) {

    data = {
      seen_pool_profile_id: currentProfileID,
      pool_id: poolID,
      right_swipe: rightSwipe,
    }

    $.ajax('<%= swipes_path %>', {
      data: data,
      complete: function(jqXHR, textStatus) {
        var data = jqXHR.responseJSON;
        if (data && data.pool_profile) {
          // no match, send next profile
          replaceCard(data.pool_profile, rightSwipe);
          currentProfileID = data.pool_profile.id;
        } else {
          $card.html("<p class='empty'>Sory, no more candidates.</p>");
          $skipBtn.hide();
          $acceptBtn.hide();
        }
        console.log(jqXHR.responseJSON,textStatus)
      },
      type: 'POST'
    });


  }

  function replaceCard(data, rightSwipe) {
    $card.css({position: 'relative'});
    if (rightSwipe) {
      var outEnd = $(window).width();
      var inStart = 0 - $(window).width() / 2 - $card.width();
    } else {
      var outEnd = 0 - $(window).width() / 2 - $card.width();
      var inStart = $(window).width();
    }

    $card.animate({left: outEnd + 'px'}, {duration: 500});
    $skipBtn.hide();
    $acceptBtn.hide();

    setTimeout(function() {

      console.log(data);

      // replace card
      var skills = data.skills && data.skills.length > 0 ?
        data.skills : "<em>No skills entered.";
      var goals = data.goals && data.goals.length > 0 ?
        data.goals : "<em>No goals entered.";
      var name = data.user.name;
      var avatar = data.user.avatar;

      $('.skills-data').html(data.skills);
      $('.goals-data').html(data.goals);
      $('.name').html(name);
      $('.avatar img').attr('src', avatar);
      $('.pod-avatars').empty();
      if (data.pod_members) {
        for(var i = 0; i < data.pod_members.length; i++) {
          $('.pod-avatars').append('<img src="' + data.pod_members[i]+ '" />');
        }
      }


      $card.css({left: inStart});
      $card.animate({left: 0}, {
        duration: 500,
        complete: function() {
          $skipBtn.fadeIn();
          $acceptBtn.fadeIn();
        }
      });
    }, 701);
  }


}(jQuery));
<% end %>
</script>

app/views/pools/new.html.erb
<% content_for :nav_left do %>
  <%= nav_item_discover "left" %>
<% end %>
<% content_for :nav_right do %>
  <%= nav_item_chat "right" %>
<% end %>

<div class="container">

  <% #Create new pool %>
  <div class="row">
    <div class="col-xs-12 col-md-4 col-md-offset-4">
      <span class="name">Add Event</span>
      <%= render partial: 'form' %>
    </div>
  </div>
</div>

app/views/pools/show.html.erb
<% if user_signed_in? %>
  <% content_for :nav_left do %>
    <%= nav_item_events "left" %>
  <% end %>
  <% content_for :nav_right do %>
    <%= nav_item_chat "right" %>
  <% end %>
<% else %>
  <nav>
    <div class="btn-group btn-group-justified">
      <a class="btn btn-default btn-name">Skana</a>
    </div>
  </nav>
<% end %>

<div class="container">

  <div class="row">
    <div class="col-xs-12 col-md-4 col-md-offset-4">
      <span class="name"><%= @pool.name %></span>
      <div class="list-group show-pool">
        <% { description: "Description",
             start_at: "Start Date", end_at: "End Date",
             location_name: "Location Name",
             location_address: "Location Address" }.each do |key, val| %>
          <span class="list-group-item">
            <h4 class="list-group-item-heading"><%= val %></h4>
            <% if key == :start_at || key == :end_at %>
              <p class="list-group-item-text">
                <%= @pool.send(key).try(:strftime, "%D %r") || "Not Available" %>
              </p>
            <% elsif key == :creator %>
              <p class="list-group-item-text">
                <%= @pool.send(key).try(:name) || "Not Available" %>
              </p>
            <% else %>
                <p class="list-group-item-text">
                  <%= @pool.send(key) || "Not Available" %>
                </p>
            <% end %>
          </span>
        <% end %>
      </div>
      <% if user_signed_in? %>
        <% unless @pool.users.exists?(id: current_user.id) %>
          <%= link_to 'Join Event', new_pool_pool_profile_path(@pool),
            class: "btn btn-primary btn-block"  %>
        <% end %>
      <% else %>
        <%= link_to 'Login with GitHub to join', user_omniauth_authorize_path(:github),
          class: "btn btn-primary btn-block"  %>
      <% end %>

    </div>
  </div>

</div>