config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  authenticated :user do
    root to: 'users#show', as: :authenticated_root
  end

  resources :users, only: [:show, :update, :edit, :destroy]

  resources :pools do
    resources :pool_profiles
    get :match
  end

  resources :pods, only: [:index, :show] do
    delete :leave
    put :messages_seen
    patch :messages_seen
  end

  resources :swipes, only: [:create]

  match "/websocket", :to => WebsocketRails::ConnectionManager.new, via: [:get, :post]

  get '/:id', to: 'pools#show'
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:github]

  has_many :messages
  has_many :swipes, -> { queue }
  has_many :seen_pool_profiles, class_name: 'PoolProfile', through: :swipes
  has_many :pools, through: :pool_profiles
  has_many :pool_profiles
  has_and_belongs_to_many :pods
  has_many :created_pools, class_name: 'Pool', foreign_key: 'creator_id'
  has_many :message_views, -> { message }, class_name: 'ResourceView'

  def self.from_omniauth(auth)
    user = where(provider: auth.provider, uid: auth.uid).first_or_initialize do |u|
      u.name = auth.info.name || auth.info.nickname
    end
    user.email = auth.info.email
    user.password = Devise.friendly_token
    user.avatar = auth.info.image # assuming the user model has an image
    user.save
    user
  end

  def self.new_with_session(params, session)
    raise StandardError.new "Hello"
    super.tap do |user|
      puts session["devise.github_data"].inspect
      if data = session["devise.github_data"] && session["devise.github_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
        user.avatar = data["info"]["image"] # assuming the user model has an image
      end
    end
  end

  def new_message_count
    total_unseen = 0

    self.pods.each do |pod|
      msg_view = self.message_views.find_by(viewable: pod)

      viewed_at = msg_view.try(:last_viewed_at)

      if viewed_at.present?
        total_unseen += pod.messages.where('created_at >= ?', viewed_at).size
      else
        total_unseen += pod.messages.all.size
      end
    end

    total_unseen
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "GitHub") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :update, :edit, :destroy]

  respond_to :html

  #def index
    #@users = User.all
    #respond_with @users
  #end

  def show
    respond_with @user
  end

  #def new
    #@user = User.new
    #respond_with @user
  #end

  #def create
    #@user = User.new user_params
    #flash[:notice] = 'User was successfully created.' if @user.save
    #respond_with @user
  #end

  def update
    flash[:notice] = 'User was successfully updated.' if @user.save
    respond_with @user
  end

  def edit
    respond_with @user
  end

  def destroy
    @user.destroy
    redirect_to :root
  end

  private

  def set_user
    @user = params[:id] ? User.find(params[:user_id]) : current_user
  end

  def user_params
    params.permit(:name)
  end

end

app/views/users/show.html.erb
<% content_for :nav_left do %>
  <%= nav_item_discover "left" %>
<% end %>
<% content_for :nav_right do %>
  <%= nav_item_chat "right" %>
<% end %>

<div class="container">

  <% # List of User pool_profiles %>
  <div class="row">
    <div class="col-xs-12 col-md-4 col-md-offset-4 custom-list">
      <div class="list-group list-pool-items">
        <a class="list-group-title">Your Open Searches</a>
        <% @user.pool_profiles.each do |profile| %>
          <%= render partial: 'shared/list_user_pool_profile',
            locals: { profile: profile } %>
        <% end %>
      </div>
      <%= link_to pools_path, class: 'btn btn-default btn-sm list-btn' do %>
        <i class="fa fa-search"></i> Event
      <% end %>
    </div>
  </div>

  <% # List of User created_pools %>
  <div class="row">
    <div class="col-xs-12 col-md-4 col-md-offset-4 custom-list">
      <div class="list-group list-pool-items">
        <a class="list-group-title">Your Events</a>
        <% @user.created_pools.each do |pool| %>
          <%= render partial: 'shared/list_user_created_pool',
            locals: { pool: pool } %>
        <% end %>
      </div>
      <%= link_to new_pool_path, class: 'btn btn-default btn-sm list-btn' do %>
        <i class="fa fa-plus"></i> Event
      <% end %>
    </div>
  </div>

</div>