config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  authenticated :user do
    root to: 'users#show', as: :authenticated_root
  end

  resources :users, only: [:show, :update, :edit, :destroy]

  resources :pools do
    resources :pool_profiles
    get :match
  end

  resources :pods, only: [:index, :show] do
    delete :leave
    put :messages_seen
    patch :messages_seen
  end

  resources :swipes, only: [:create]

  match "/websocket", :to => WebsocketRails::ConnectionManager.new, via: [:get, :post]

  get '/:id', to: 'pools#show'
end

app/views/shared/_list_pod.html.erb
<div class="list-group-item">
  <%= link_to pod_path(pod.id), class: "list-item-name" do %>
    <span><%= pod.pool.name %></span>
    <span class="no-float badge badge-primary">
      <%= pod.users.size %>
    </span>
  <% end %>
  <%= link_to pod_leave_path(pod),
    class: "btn btn-primary", method: "DELETE" do %>
    <span>
        <i class="fa fa-remove"></i>
    </span>
  <% end %>
</div>

app/views/shared/_list_pool.html.erb
<%= link_to pool_path(pool), class: "list-group-item" do %>
  <%= pool.name %>
  <span class="badge badge-primary">
    <%= pool.users.size %>
  <i class="fa fa-user"></i>
  </span>
<% end %>

app/views/shared/_list_user_created_pool.html.erb
<div class="list-group-item">
  <span class="list-item-name"><%= pool.name %></span>
  <%= link_to edit_pool_path(pool),
    class: "btn btn-primary" do %>
    <span>
        <i class="fa fa-edit"></i>
    </span>
  <% end %>
</div>

app/views/shared/_list_user_pool_profile.html.erb
<div class="list-group-item">
  <%= link_to pool_match_path(profile.pool), class: "list-item-name" do %>
    <span><%= profile.pool.name %></span>
  <% end %>
  <%= link_to edit_pool_pool_profile_path(profile.pool, profile),
    class: "btn btn-primary" do %>
    <span>
        <i class="fa fa-edit"></i>
    </span>
  <% end %>
  <%= link_to pool_path(profile.pool),
    class: "btn btn-primary" do %>
    <span>
        <i class="fa fa-info"></i>
    </span>
  <% end %>
</div>

app/views/shared/_nav.html.erb
<nav>
  <div class="btn-group btn-group-justified">
    <%= yield :nav_left %>
    <a class="btn btn-default btn-name">Skana</a>
    <%= yield :nav_right %>
  </div>
</nav>

app/views/shared/_scripts.html.erb
<script>

  (function(global) {

    var url = "<%= root_url.gsub(/https?:\/\//, "") %>";
    var eventAggregator = $('body');
    var $chatNotification = $('.chat-notification').length === 0 ?
      null : $('.chat-notification')

    global.Skana = global.Skana || {};

    global.Skana.socketManager = webSocketManager(url, eventAggregator);
    global.Skana.socketManager.matchListener(<%= current_user.pools.pluck :id %>);
    global.Skana.socketManager.messageListener(<%= current_user.pods.pluck :id %>);

    global.Skana.chatNotifier = chatNotificationService(eventAggregator,
      <%= current_user.new_message_count %>, $chatNotification)
    global.Skana.chatNotifier.start();
    <%= yield :stop_chat_notifier %>

  }(this));

</script